### ISSUE TITLE
Kanban Board: Recipe app 

### ISSUE THREAD

**Issue by Mutai-Gilbert** [atok624/Recipe-App#12]
Highlights

The following people are assigned to each task.

@Mutai-Gilbert 
@atok624 

[Github Project Link](https://github.com/users/atok624/projects/2)

Note: We are two in a team.

**Comment by Davidosky007** [comment]
Hi @Mutai-Gilbert @atok624 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
## Highlights
* All team members info provided 👍 
* Link to Kanban board works 👍 
* Cards shared evenly 👍 

## Required Changes ♻️
* Kindly add the missing column (in review ) as [its required ](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/setup_kanban_board.md#:~:text=Open%20the%20GitHub,read%20them%20carefully.)
![image](https://github.com/atok624/Recipe-App/assets/52497246/5d6a3b0e-a577-4bcd-9671-301bb4757b09)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Mutai-Gilbert** [comment]
Done.

**Comment by elisha2kyakpo1** [comment]
Hi 👋 @Mutai-Gilbert, and @atok624, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights

👍 You did well to add the column which was missing as required by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
